### ISSUE TITLE
TypeError("print_exception() got an unexpected keyword argument 'etype'")

### ISSUE THREAD

**Issue by hopejuju** [nctu-eva-lab/3DV-2022#11]
Hi TA,

I don't have an idea about the following issue. 
I didn'r change any part of code and I found a lots information on google, but I still cannot solve it.
Please help to clarify.

The error occurred after I run  python train.py dtype='voxel'.

/home/odie/3DV-2022/data/chair_img_pc_voxel_mesh
Starting training !
Error executing job with overrides: ['dtype=voxel']
An error occurred during Hydra's exception formatting:
TypeError("print_exception() got an unexpected keyword argument 'etype'")
Traceback (most recent call last):
  File "/home/hscc/anaconda3/envs/py3d/lib/python3.10/site-packages/hydra/_internal/utils.py", line 283, in run_and_report
    print_exception(etype=None, value=ex, tb=final_tb)  # type: ignore
TypeError: print_exception() got an unexpected keyword argument 'etype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hscc/Desktop/yachu/3DV-2022/train.py", line 97, in <module>
    train_model()
  File "/home/hscc/anaconda3/envs/py3d/lib/python3.10/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/home/hscc/anaconda3/envs/py3d/lib/python3.10/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/home/hscc/anaconda3/envs/py3d/lib/python3.10/site-packages/hydra/_internal/utils.py", line 294, in run_and_report
    raise ex
  File "/home/hscc/anaconda3/envs/py3d/lib/python3.10/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/hscc/anaconda3/envs/py3d/lib/python3.10/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/home/hscc/anaconda3/envs/py3d/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/home/hscc/anaconda3/envs/py3d/lib/python3.10/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/hscc/anaconda3/envs/py3d/lib/python3.10/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/hscc/Desktop/yachu/3DV-2022/train.py", line 61, in train_model
    if step % len(train_loader) == 0: #restart after one epoch
ZeroDivisionError: integer division or modulo by zero

**Comment by Nemo1999** [comment]
Hi @hopejuju
Maybe you can try to deal with ZeroDivisionError first.
I think the "etype"  bug is from upstream.

**Comment by hopejuju** [comment]
Hi TA,

Thank you for help.
I solve this error successfully.

**Comment by anbaoxu1** [comment]
Hello, may I ask how this issue was resolved? Can you share it? Thank you very much
